version: "3.8"

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: movie_web_user
      POSTGRES_DB: movie_web_backend
      POSTGRES_PASSWORD: YourPasswordHere
    ports:
      - "5412:5432" 
    networks:
      - movieweb-backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie_web_user -d movie_web_backend"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    ports:
      - "3432:80"
    depends_on:
      - db
    networks:
      - movieweb-backend-network
    env_file:
      - stack.env

networks:
  movieweb-backend-network: 
    driver: bridge
