version: "3.8"

services:


  movieweb-db:
    image: postgres
    ports:
      - "5412:5432" 
    env_file:
      - stack.env

  movieweb-backend:
    build:
      context: .
    ports:
      - "3432:80"
    depends_on:
      - movieweb-db
    env_file:
      - stack.env
