version: "3.8"

services:

  db:
    image: postgres
    # environment:
    #   POSTGRES_USER: movie_web_user
    #   POSTGRES_DB: movie_web_backend
    #   POSTGRES_PASSWORD: YourPasswordHere
    ports:
      - "5432:5432" 
    networks:
      - movieweb-backend-network

  backend:
    build:
      context: .
    ports:
      - "3432:80"
    depends_on:
      - db
    networks:
      - movieweb-backend-network
    env_file:
      - stack.env

networks:
  movieweb-backend-network: 
    driver: bridge
