version: "3.8"

services:

  db:
    image: postgres
    ports:
      - "5412:5432" 
    networks:
      - movieweb-backend-network
    env_file:
      - stack.env

  backend:
    build:
      context: .
    ports:
      - "3432:80"
    depends_on:
      - db
    networks:
      - movieweb-backend-network
    env_file:
      - stack.env

networks:
  movieweb-backend-network: 
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
