version: "3.8"

services:

  movieweb-backend:
    build:
      context: .
    environment:
      MWB_POSTGRES__CONNECTION: postgresql://movie_web_user:YourPasswordHere@movieweb-db:5412/movie_web_backend
      MWB_CRYPTO__SESSION_SECRET: 32CharacterLongStringHere 
      MWB_META__NAME: unofficial-sudo-flix 
      MWB_POSTGRES__MIGRATE_ON_BOOT: "true"
      MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS: "true" 
    ports:
      - "3432:80"
    depends_on:
      - movieweb-db
    networks:
      - movieweb-backend-network
    env_file:
      - stack.env


  movieweb-db:
    image: postgres
    environment:
      POSTGRES_USER: movie_web_user 
      POSTGRES_DB: movie_web_backend 
      POSTGRES_PASSWORD: YourPasswordHere 
    ports:
      - "5412:5432" 
    networks:
      - movieweb-backend-network
    env_file:
      - stack.env

networks:
  movieweb-backend-network: 
    driver: bridge
